"""Application constants."""

# Validation defaults
DEFAULT_MIN_ODDS = 1.10
DEFAULT_MAX_ODDS = 9.99
DEFAULT_MIN_PROFIT = -1.0
DEFAULT_MAX_PROFIT = 25.0
DEFAULT_MIN_EVENT_TIME = 0  # seconds

# Rate limiting
DEFAULT_REQUESTS_PER_SECOND = 2
DEFAULT_BASE_INTERVAL = 0.5  # seconds
DEFAULT_MAX_INTERVAL = 5.0  # seconds

# Cache settings
DEFAULT_CACHE_TTL = 10  # seconds
DEFAULT_CACHE_MAX_SIZE = 2000

# Telegram
DEFAULT_MAX_QUEUE_SIZE = 1000
DEFAULT_MAX_RETRIES = 3

# Redis
DEFAULT_CURSOR_KEY = "retador:cursor"
DEFAULT_PICK_PREFIX = "pick:"

# Processing
DEFAULT_CONCURRENT_PICKS = 250
DEFAULT_CONCURRENT_REQUESTS = 100
